### ISSUE TITLE
Google Login on website is not configured or not working

### ISSUE THREAD

**Issue by HugoGresse** [paug/android-makers-2022#132]
**Describe the bug**
hoverboard allow users to add talks to their own list, linked to their account on Firebase.
The account used is Google, but for android-makers-2022, the configuration for Google is missing: 

The error when calling Google identify toolkit is 

  |  
-- | --
error | Object { code: 400, message: "CONFIGURATION_NOT_FOUND", errors: […] }
code | 400
message | "CONFIGURATION_NOT_FOUND"
errors | [ {…} ]
0 | Object { message: "CONFIGURATION_NOT_FOUND", domain: "global", reason: "invalid" }
message | "CONFIGURATION_NOT_FOUND"
domain | "global"
reason | "invalid"

I belive it is maybe jsut either the google login is not enable on the firebase project, or some misconfiguration. 

**To Reproduce**

1. Go to https://androidmakers.fr/schedule/2022-04-26?sessionId=SGC-3820&sessionId=DIA-1089
2. Click on bookmark button
3. Click on Sign in at the bottom right
4. Error is displayed in dev console, login does not complet

**Desktop (please complete the following information):**

- OS: mac
- Browser: Firefox 100

**Comment by benju69** [comment]
Yep I know
I activated the login this morning but My Schedule seems broken
you can follow this issue https://github.com/gdg-x/hoverboard/issues/2364
Otherwise an alternate solution is to have a script like a 2020, to add sessions to google calendar, but now it's typescript, not javascript :s

**Comment by HugoGresse** [comment]
Erf, is seems on works on SunnyTech schedule : https://sunny-tech.io/schedule/
The fork update is from September 2021 though.

**Comment by abraham** [comment]
I think you need this change.

https://github.com/gdg-x/hoverboard/commit/a1541b1d5529f485b7c3e4315d3faa3dfd53492d#diff-1a8c8378553dfd6438608db25b054dd546669c2958d8952480d6304136411735

**Comment by benju69** [comment]
Yes now it works :)
